.TH ZORK3 6 "August 2026" "Zork III" "Games Manual"
.SH NAME
zork3 \- play Zork III: The Dungeon Master
.SH SYNOPSIS
.B zork3
.RI [ frotz-options ]
.SH DESCRIPTION
.B zork3
starts Zork III using the Frotz Z-machine interpreter.
The game is an interactive-fiction adventure controlled by typed commands.
.PP
The packaged story file is installed at
.IR /usr/share/games/zork3/zork3.z3 .
.SH OPTIONS
Options are passed directly to
.BR frotz (6)
before the story-file argument.
.SH FILES
.TP
.I /usr/share/games/zork3/zork3.z3
Z-machine version 3 story image supplied by upstream.
.SH SEE ALSO
.BR frotz (6),
.BR dfrotz (6)
.SH HOMEPAGE
https://github.com/historicalsource/zork3
